ac_zone:
  module: ac_zone
  global: true

ac_controller:
  module: ac_controller
  class: AirconController
  dependencies:
    - ac_zone

  bedroom:
    temperature_entity_id: b1
    switch_entity_id: 
    state_entity_id: se1
    priority: 1
    switch_reverse_entity_id:
  kitchen:
    temperature_entity_id: b2
    switch_entity_id: s2
    state_entity_id: se2
    priority: 2
  study:
    temperature_entity_id: b3
    switch_entity_id: s3
    state_entity_id: se3
    priority: 1

  desired_temperature_helper_id: desired_temperature_helper_id
  trigger_threshold_helper_id: trigger_theshold_helper_id
  power_on_strategy: all / any
  power_switch_entity_id: power_entity_id
  mode: heating/cooling
  self_fix_toggle_entity_id: self_fix_toggle_entity_id

switch_state_manager:
  module: ac_switch_state_manager
  class: ACSwitchStateManager
  use_dictionary_unpacking: true
  dependencies:
    - ac_zone
  bedroom:
    switch_entity_id: s1
    state_entity_id: se1
    switch_reverse_entity_id:
  kitchen:
    switch_entity_id: s2
    state_entity_id: se2
  study:
    switch_entity_id: s3
    state_entity_id: se3
